import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextAuthSessionPorovider from "./providers/NextAuthSessionPorovider";
import Navbar from "./components/Navbar";
import { ThemeProvider } from "next-themes";
const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

export const metadata = {
   title: "My next.js app",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en" suppressHydrationWarning>
         <NextAuthSessionPorovider>
            <body className={`${geistSans.variable} ${geistMono.variable} max-w-7xl mx-auto pt-24 antialiased`}>
               <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                  <Navbar />
                  <main>{children}</main>
               </ThemeProvider>
            </body>
         </NextAuthSessionPorovider>
      </html>
   );
}
